name: review
on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npx yarn
      - run: npx yarn lint

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npx yarn
      - run: npx yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: pr-${{ github.event.number }}-build
          path: dist/webext-prod/
